version: '3'

services:
    app:
        build:
            context: .
            dockerfile: dockerfile-nodemon
        volumes:
            - ./src:/app/src:ro
            - ../frontend/build:/app/static:ro
        ports:
            - 3000:3000

    test-runner:
        build:
            context: .
            dockerfile: dockerfile-test-runner
        volumes:
            - ./src:/app/src:ro
            - ./test:/app/test:ro
            - ./jest.config.js:/app/jest.config.js:ro
