FROM node:10.16.1-alpine

WORKDIR /app
COPY package.json package-lock.json tsconfig.json ./
COPY test/ ./test/
COPY src/ ./src/
RUN npm i && npm run build

FROM node:10.16.1-alpine

RUN apk add curl
RUN addgroup appuser && adduser -S -G appuser
USER appuser

WORKDIR /app
COPY ./static ./static
# If any revision info is present, copy it into here.
COPY revinfo* .

COPY --from=0 /app/package.json ./package.json
COPY --from=0 /app/dist ./dist

RUN npm i --production

HEALTHCHECK CMD curl --fail http://localhost:3000 || exit 1

CMD ["node", "dist/src/index.js"]
