version: 2
jobs:
  test-backend:
    docker:
      - image: node:lts-alpine
    
    working_directory: ~/private-note/backend

    steps:
      - run: apk add ca-certificates git openssh-client
      - run: |
          cd ~/private-note
          rm -rf *
          git clone https://github.com/CatEars/private-note.git .

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm test
      - run: npm run build
      - persist_to_workspace:
          root: ~/private-note
          paths: .

  test-frontend:
    docker:
      - image: node:lts-alpine

    working_directory: ~/private-note/frontend
    steps:
      - run: apk add ca-certificates git openssh-client
      - run: |
          cd ~/private-note
          rm -rf *
          git clone https://github.com/CatEars/private-note.git .

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm test-ci
      - run: npm run build
      - persist_to_workspace:
          root: ~/private-note
          paths: .

workflows:
  version: 2
  build:
    jobs:
      - test-frontend:
          filters:
            tags:
              only: /.*/
      - test-backend:
          filters:
            tags:
              only: /.*/
