version: 2
jobs:
  test-backend:
    docker:
      - image: node:lts-alpine

    working_directory: ~/private-note/backend

    steps:
      - run:
          name: Install Dependencies
          command: apk add ca-certificates git openssh-client
      - run:
          name: Clone Repository
          command: |
            cd ~/private-note
            rm -rf *
            git clone https://github.com/CatEars/private-note.git .

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm test
      - run: npm run build
      - persist_to_workspace:
          root: ~/private-note
          paths: .

  deploy-docker:
    docker:
      - image: node:lts-alpine
    working_directory: ~/private-note
    steps:
      - run:
          name: Install Dependencies
          command: apk add ca-certificates git openssh-client docker curl
      - checkout
      - setup_remote_docker
      - run:
          name: Build app and push image
          command: |
            cd frontend
            npm ci
            npm run build:styles
            npm run build
            cp -r build ../backend/static
            cd ../backend
            npm ci
            ./print_rev_info.sh > revinfo.txt
            docker build . -t catears/private-note:${CIRCLE_BRANCH:1} -f dockerfile-private-note
            echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin
            docker tag catears/private-note:${CIRCLE_BRANCH:1} catears/private-note:latest
            docker push catears/private-note:${CIRCLE_BRANCH:1}
            docker push catears/private-note:latest
            curl -X POST $MICROBADGER_WEBHOOK

  test-frontend:
    docker:
      - image: node:lts-alpine

    working_directory: ~/private-note/frontend
    steps:
      - run:
          name: Install Dependencies
          command: apk add ca-certificates git openssh-client
      - run:
          name: Clone Repository
          command: |
            cd ~/private-note
            rm -rf *
            git clone https://github.com/CatEars/private-note.git .

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run test-ci
      - run: npm run build
      - run: npm run build:styles
      - persist_to_workspace:
          root: ~/private-note
          paths: .

  test-both:
    docker:
      - image: node:lts-alpine

    working_directory: ~/private-note
    steps:
      - run:
          name: Install Dependencies
          command: apk add ca-certificates git openssh-client
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run pretty-check
      - persist_to_workspace:
          root: ~/private-note
          paths: .

workflows:
  version: 2
  build:
    jobs:
      - test-both:
          filters:
            branches:
              only: /.*/
      - test-frontend:
          filters:
            branches:
              only: /.*/
      - test-backend:
          filters:
            branches:
              only: /.*/
      - deploy-docker:
          requires:
            - test-frontend
            - test-backend
            - test-both
          filters:
            branches:
              only: /^v[0-9]+\.[0-9]+.[0-9]+.*/
