version: 2
jobs:
  test-backend:
    docker:
      - image: node:lts-alpine
    
    working_directory: ~/private-note/backend

    steps:
      - run: apk add ca-certificates git openssh-client
      - checkout:
          path: ~/private-note

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm test
      - run: npm run build
      - run: cd ..
      - persist_to_workspace:
          root: ~/repo
          paths: .

  test-frontend:
    docker:
      - image: node:lts-alpine

    working_directory: ~/private-note/frontend
    steps:
      - run: apk add ca-certificates git openssh-client
      - checkout:
          path: ~/private-note

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm test
      - run: npm run build
      - run: cd ..
      - persist_to_workspace:
          root: ~/repo
          paths: .

workflows:
  version: 2
  build:
    jobs:
      - test-frontend:
          filters:
            tags:
              only: /.*/
      - test-backend:
          filters:
            tags:
              only: /.*/
