version: '3'

services:
  docs:
    image: squidfunk/mkdocs-material

    ports:
      - 8000:8000

    volumes:
      - ./:/docs:ro

  build:
    image: squidfunk/mkdocs-material
    command: build

    volumes:
      - ./:/docs
