name: ci

on: push

jobs:
  test-backend:
    name: Run CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Install dependencies
        working-directory: backend
        run: |
          npm ci

      - uses: actions/cache@v1
        working-directory: backend
        with:
          path: node_modules
          key: node_modules-backend-v1-${{ hashFiles('**/package-lock.json') }}

      - name: Run tests
        working-directory: backend
        run: |
          npm test
