name: Build Docker

on:
  push:
    branches:
      - 'v*'

jobs:
  deploy-docker:
    name: Update Docker Image on Tags
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        id: extract_branch
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - uses: actions/cache@v1
        with:
          path: ./backend/node_modules
          key: node_modules-backend-v1-${{ hashFiles('backend/**/package-lock.json') }}
      - uses: actions/cache@v1
        with:
          path: ./frontend/node_modules
          key: node_modules-frontend-v1-${{ hashFiles('frontend/**/package-lock.json') }}
      - name: Build App Image
        run: |
          cd frontend
          npm ci
          npm run build:styles
          npm run build
          cp -r build ../backend/static
          cd ../backend
          npm ci
          ./print_rev_info.sh > revinfo.txt
      - name: Publish Docker Image To Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: catears/private-note
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: dockerfile-private-note
          workdir: ./backend
          tags: ${{ steps.extract_branch.output.branch }},latest
